server:
  port: 8520
#postgresql
spring:
  datasource:
    driver-class-name:  org.postgresql.Driver
    jdbc-url: jdbc:postgresql://192.168.154.64:21191/study_map_tool?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true
    username: postgres
    password: sjgt_2020