server:
  port: 9085
  servlet:
    context-path: /study_map_tool_server
#postgresql
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://192.168.154.32:21191/study_map_tool?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true
    username: postgres
    password: sjgt_2020
file_path: E:/test/

